//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.CloudERP {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Common() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.CloudERP.Common.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Actions.
        /// </summary>
        public static string Actions
        {
            get
            {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Back to List.
        /// </summary>
        public static string BackToList
        {
            get
            {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Create.
        /// </summary>
        public static string Create
        {
            get
            {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string Delete
        {
            get
            {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Details.
        /// </summary>
        public static string Details
        {
            get
            {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string Edit
        {
            get
            {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string Save
        {
            get
            {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Succeed.
        /// </summary>
        public static string Succeed
        {
            get
            {
                return ResourceManager.GetString("Succeed", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на UAH.
        /// </summary>
        public static string UAH
        {
            get
            {
                return ResourceManager.GetString("UAH", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Update.
        /// </summary>
        public static string Update
        {
            get
            {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
