//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т. д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените RESX-файл и снова запустите ResGen
    // с параметром /str или перестройте проект Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Miscellaneous {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Miscellaneous() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Miscellaneous", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Переопределяет свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account Controls.
        /// </summary>
        internal static string AccountControls {
            get {
                return ResourceManager.GetString("AccountControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account Flow.
        /// </summary>
        internal static string AccountFlow {
            get {
                return ResourceManager.GetString("AccountFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account Heads.
        /// </summary>
        internal static string AccountHeads {
            get {
                return ResourceManager.GetString("AccountHeads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account Settings.
        /// </summary>
        internal static string AccountSettings {
            get {
                return ResourceManager.GetString("AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accounts Ledger.
        /// </summary>
        internal static string AccountsLedger {
            get {
                return ResourceManager.GetString("AccountsLedger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account Sub Controls.
        /// </summary>
        internal static string AccountSubControls {
            get {
                return ResourceManager.GetString("AccountSubControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account Title.
        /// </summary>
        internal static string AccountTitle {
            get {
                return ResourceManager.GetString("AccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Category.
        /// </summary>
        internal static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Product.
        /// </summary>
        internal static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Admin Guide.
        /// </summary>
        internal static string AdminGuide {
            get {
                return ResourceManager.GetString("AdminGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All Categories.
        /// </summary>
        internal static string AllCategories {
            get {
                return ResourceManager.GetString("AllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All Customers.
        /// </summary>
        internal static string AllCustomers {
            get {
                return ResourceManager.GetString("AllCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All Financial Years.
        /// </summary>
        internal static string AllFinancialYears {
            get {
                return ResourceManager.GetString("AllFinancialYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All Purchases.
        /// </summary>
        internal static string AllPurchases {
            get {
                return ResourceManager.GetString("AllPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All Sales.
        /// </summary>
        internal static string AllSales {
            get {
                return ResourceManager.GetString("AllSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All Suppliers.
        /// </summary>
        internal static string AllSuppliers {
            get {
                return ResourceManager.GetString("AllSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Area.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Balance Sheet.
        /// </summary>
        internal static string BalanceSheet {
            get {
                return ResourceManager.GetString("BalanceSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Branch Customers.
        /// </summary>
        internal static string BranchCustomers {
            get {
                return ResourceManager.GetString("BranchCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Branches.
        /// </summary>
        internal static string Branches {
            get {
                return ResourceManager.GetString("Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Branch`s.
        /// </summary>
        internal static string Branchs {
            get {
                return ResourceManager.GetString("Branchs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Branch Suppliers.
        /// </summary>
        internal static string BranchSuppliers {
            get {
                return ResourceManager.GetString("BranchSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Branch.
        /// </summary>
        internal static string BranchTitle {
            get {
                return ResourceManager.GetString("BranchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Case / &lt;br/&gt; Bank Balance.
        /// </summary>
        internal static string CaseBankBalance {
            get {
                return ResourceManager.GetString("CaseBankBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category Name.
        /// </summary>
        internal static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category.
        /// </summary>
        internal static string CategoryTitle {
            get {
                return ResourceManager.GetString("CategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click here to choose a correct address below.
        /// </summary>
        internal static string ClickHereToChooseACorrectAddressBelow {
            get {
                return ResourceManager.GetString("ClickHereToChooseACorrectAddressBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Companies.
        /// </summary>
        internal static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Companies.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Company Registration.
        /// </summary>
        internal static string CompanyRegistration {
            get {
                return ResourceManager.GetString("CompanyRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Company.
        /// </summary>
        internal static string CompanyTitle {
            get {
                return ResourceManager.GetString("CompanyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contact №.
        /// </summary>
        internal static string ContactNo {
            get {
                return ResourceManager.GetString("ContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Credit.
        /// </summary>
        internal static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current Month &lt;br/&gt; Expenses.
        /// </summary>
        internal static string CurrentMonthExpenses {
            get {
                return ResourceManager.GetString("CurrentMonthExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current Month &lt;br/&gt; Recovery.
        /// </summary>
        internal static string CurrentMonthRecovery {
            get {
                return ResourceManager.GetString("CurrentMonthRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current Month &lt;br/&gt; Revenue.
        /// </summary>
        internal static string CurrentMonthRevenue {
            get {
                return ResourceManager.GetString("CurrentMonthRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current Purchase Unit Price.
        /// </summary>
        internal static string CurrentPurchaseUnitPrice {
            get {
                return ResourceManager.GetString("CurrentPurchaseUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current Qty.
        /// </summary>
        internal static string CurrentQty {
            get {
                return ResourceManager.GetString("CurrentQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customer Full Name.
        /// </summary>
        internal static string CustomerFullName {
            get {
                return ResourceManager.GetString("CustomerFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customer.
        /// </summary>
        internal static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customers.
        /// </summary>
        internal static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dashboard.
        /// </summary>
        internal static string DashboardTitle {
            get {
                return ResourceManager.GetString("DashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Debit.
        /// </summary>
        internal static string Debit {
            get {
                return ResourceManager.GetString("Debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Designation.
        /// </summary>
        internal static string Designation {
            get {
                return ResourceManager.GetString("Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit Category.
        /// </summary>
        internal static string EditCategory {
            get {
                return ResourceManager.GetString("EditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Employee Registration.
        /// </summary>
        internal static string EmployeeRegistration {
            get {
                return ResourceManager.GetString("EmployeeRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Employees.
        /// </summary>
        internal static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Employee Statistics.
        /// </summary>
        internal static string EmployeeStatistics {
            get {
                return ResourceManager.GetString("EmployeeStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter Amount.
        /// </summary>
        internal static string EnterAmount {
            get {
                return ResourceManager.GetString("EnterAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter New Category Name.
        /// </summary>
        internal static string EnterNewCategoryName {
            get {
                return ResourceManager.GetString("EnterNewCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter Reason.
        /// </summary>
        internal static string EnterReason {
            get {
                return ResourceManager.GetString("EnterReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Expiry Date.
        /// </summary>
        internal static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Financial Year.
        /// </summary>
        internal static string FinancialYear {
            get {
                return ResourceManager.GetString("FinancialYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Forecasting.
        /// </summary>
        internal static string Forecasting {
            get {
                return ResourceManager.GetString("Forecasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General Transaction.
        /// </summary>
        internal static string GeneralTransaction {
            get {
                return ResourceManager.GetString("GeneralTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Get Trial Balance.
        /// </summary>
        internal static string GetTrialBalance {
            get {
                return ResourceManager.GetString("GetTrialBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Guide.
        /// </summary>
        internal static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hello,.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Income Statement.
        /// </summary>
        internal static string IncomeStatement {
            get {
                return ResourceManager.GetString("IncomeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Income Statement.
        /// </summary>
        internal static string IncomeStatementStr {
            get {
                return ResourceManager.GetString("IncomeStatementStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invoice №.
        /// </summary>
        internal static string InvoiceNo {
            get {
                return ResourceManager.GetString("InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Item Detail.
        /// </summary>
        internal static string ItemDetail {
            get {
                return ResourceManager.GetString("ItemDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Items.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Journal.
        /// </summary>
        internal static string Journal {
            get {
                return ResourceManager.GetString("Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Journal (By Transactions Date).
        /// </summary>
        internal static string JournalByTransactionsDate {
            get {
                return ResourceManager.GetString("JournalByTransactionsDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main Employee Guide.
        /// </summary>
        internal static string MainEmployeeGuide {
            get {
                return ResourceManager.GetString("MainEmployeeGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manufacture Date.
        /// </summary>
        internal static string ManufactureDate {
            get {
                return ResourceManager.GetString("ManufactureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Net Income.
        /// </summary>
        internal static string NetIncome {
            get {
                return ResourceManager.GetString("NetIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Net Profit / &lt;br/&gt; Loss.
        /// </summary>
        internal static string NetProfitLoss {
            get {
                return ResourceManager.GetString("NetProfitLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Branch.
        /// </summary>
        internal static string NewBranch {
            get {
                return ResourceManager.GetString("NewBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Customer.
        /// </summary>
        internal static string NewCustomer {
            get {
                return ResourceManager.GetString("NewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Financial Year.
        /// </summary>
        internal static string NewFinancialYear {
            get {
                return ResourceManager.GetString("NewFinancialYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New General Transaction.
        /// </summary>
        internal static string NewGeneralTransaction {
            get {
                return ResourceManager.GetString("NewGeneralTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Purchase.
        /// </summary>
        internal static string NewPurchase {
            get {
                return ResourceManager.GetString("NewPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Sale.
        /// </summary>
        internal static string NewSale {
            get {
                return ResourceManager.GetString("NewSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Supplier.
        /// </summary>
        internal static string NewSupplier {
            get {
                return ResourceManager.GetString("NewSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No forecast data available..
        /// </summary>
        internal static string NoForecastDataAvailable_ {
            get {
                return ResourceManager.GetString("NoForecastDataAvailable.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paid Purchases.
        /// </summary>
        internal static string PaidPurchases {
            get {
                return ResourceManager.GetString("PaidPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paid Salaries History.
        /// </summary>
        internal static string PaidSalariesHistory {
            get {
                return ResourceManager.GetString("PaidSalariesHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paid Sales.
        /// </summary>
        internal static string PaidSales {
            get {
                return ResourceManager.GetString("PaidSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Payroll.
        /// </summary>
        internal static string Payroll {
            get {
                return ResourceManager.GetString("Payroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Photo.
        /// </summary>
        internal static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Privacy Policy.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product Details.
        /// </summary>
        internal static string ProductDetails {
            get {
                return ResourceManager.GetString("ProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product Name.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Purchase Pending&lt;br/&gt;Payment.
        /// </summary>
        internal static string PurchasePendingPayment {
            get {
                return ResourceManager.GetString("PurchasePendingPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Purchases.
        /// </summary>
        internal static string Purchases {
            get {
                return ResourceManager.GetString("Purchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Purchases Payment Paid.
        /// </summary>
        internal static string PurchasesPaymentPaid {
            get {
                return ResourceManager.GetString("PurchasesPaymentPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Purchases Payment Pending.
        /// </summary>
        internal static string PurchasesPaymentPending {
            get {
                return ResourceManager.GetString("PurchasesPaymentPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Purchases Return.
        /// </summary>
        internal static string PurchasesReturn {
            get {
                return ResourceManager.GetString("PurchasesReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retrieve Income Statement.
        /// </summary>
        internal static string RetrieveIncomeStatement {
            get {
                return ResourceManager.GetString("RetrieveIncomeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retrieve Ledger.
        /// </summary>
        internal static string RetrieveLedger {
            get {
                return ResourceManager.GetString("RetrieveLedger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retrieve Transactions.
        /// </summary>
        internal static string RetrieveTransactions {
            get {
                return ResourceManager.GetString("RetrieveTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return Payment&lt;br/&gt;Pending.
        /// </summary>
        internal static string ReturnPaymentPending {
            get {
                return ResourceManager.GetString("ReturnPaymentPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return Purchases.
        /// </summary>
        internal static string ReturnPurchases {
            get {
                return ResourceManager.GetString("ReturnPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return Purchases Payment Paid.
        /// </summary>
        internal static string ReturnPurchasesPaymentPaid {
            get {
                return ResourceManager.GetString("ReturnPurchasesPaymentPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return Purchases Payment Pending.
        /// </summary>
        internal static string ReturnPurchasesPaymentPending {
            get {
                return ResourceManager.GetString("ReturnPurchasesPaymentPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return Sales.
        /// </summary>
        internal static string ReturnSales {
            get {
                return ResourceManager.GetString("ReturnSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return Sales Payment Paid.
        /// </summary>
        internal static string ReturnSalesPaymentPaid {
            get {
                return ResourceManager.GetString("ReturnSalesPaymentPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return Sales Payment Pending.
        /// </summary>
        internal static string ReturnSalesPaymentPending {
            get {
                return ResourceManager.GetString("ReturnSalesPaymentPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return Sales&lt;br/&gt;Pending Amount.
        /// </summary>
        internal static string ReturnSalesPendingAmount {
            get {
                return ResourceManager.GetString("ReturnSalesPendingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return Sales / Return Purchases.
        /// </summary>
        internal static string ReturnSalesReturnPurchases {
            get {
                return ResourceManager.GetString("ReturnSalesReturnPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sale Pending Payment.
        /// </summary>
        internal static string SalePendingPayment {
            get {
                return ResourceManager.GetString("SalePendingPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sale Return.
        /// </summary>
        internal static string SaleReturn {
            get {
                return ResourceManager.GetString("SaleReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sales.
        /// </summary>
        internal static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sales Payment Paid.
        /// </summary>
        internal static string SalesPaymentPaid {
            get {
                return ResourceManager.GetString("SalesPaymentPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sales Payment Pending.
        /// </summary>
        internal static string SalesPaymentPending {
            get {
                return ResourceManager.GetString("SalesPaymentPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sales / Purchases.
        /// </summary>
        internal static string SalesPurchases {
            get {
                return ResourceManager.GetString("SalesPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sale Unit Price.
        /// </summary>
        internal static string SaleUnitPrice {
            get {
                return ResourceManager.GetString("SaleUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Credit Account.
        /// </summary>
        internal static string SelectAccountCredit {
            get {
                return ResourceManager.GetString("SelectAccountCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Debit Account.
        /// </summary>
        internal static string SelectAccountDebit {
            get {
                return ResourceManager.GetString("SelectAccountDebit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Category.
        /// </summary>
        internal static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Financial Year.
        /// </summary>
        internal static string SelectFinancialYear {
            get {
                return ResourceManager.GetString("SelectFinancialYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select From Date.
        /// </summary>
        internal static string SelectFromDate {
            get {
                return ResourceManager.GetString("SelectFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Range (From Date and To Date).
        /// </summary>
        internal static string SelectRangeFromDateAndToDate {
            get {
                return ResourceManager.GetString("SelectRangeFromDateAndToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select To Date.
        /// </summary>
        internal static string SelectToDate {
            get {
                return ResourceManager.GetString("SelectToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stock Categories.
        /// </summary>
        internal static string StockCategories {
            get {
                return ResourceManager.GetString("StockCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stock Details.
        /// </summary>
        internal static string StockDetails {
            get {
                return ResourceManager.GetString("StockDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stocks.
        /// </summary>
        internal static string Stocks {
            get {
                return ResourceManager.GetString("Stocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sub Branch Accounts Ledger.
        /// </summary>
        internal static string SubBranchAccountsLedger {
            get {
                return ResourceManager.GetString("SubBranchAccountsLedger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sub Branch Customer.
        /// </summary>
        internal static string SubBranchCustomer {
            get {
                return ResourceManager.GetString("SubBranchCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sub Branch Customers.
        /// </summary>
        internal static string SubBranchCustomers {
            get {
                return ResourceManager.GetString("SubBranchCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sub Branch Income Statement.
        /// </summary>
        internal static string SubBranchIncomeStatement {
            get {
                return ResourceManager.GetString("SubBranchIncomeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sub Branch Journal (By Transactions Date).
        /// </summary>
        internal static string SubBranchJournalByTransactionsDate {
            get {
                return ResourceManager.GetString("SubBranchJournalByTransactionsDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sub Branches.
        /// </summary>
        internal static string SubBranchs {
            get {
                return ResourceManager.GetString("SubBranchs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sub Branch Suppliers.
        /// </summary>
        internal static string SubBranchSuppliers {
            get {
                return ResourceManager.GetString("SubBranchSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Get Forecast.
        /// </summary>
        internal static string SubmitForecast {
            get {
                return ResourceManager.GetString("SubmitForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Submit Transaction.
        /// </summary>
        internal static string SubmitTransaction {
            get {
                return ResourceManager.GetString("SubmitTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Suppliers.
        /// </summary>
        internal static string Suppliers {
            get {
                return ResourceManager.GetString("Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Support.
        /// </summary>
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tasks List.
        /// </summary>
        internal static string TasksList {
            get {
                return ResourceManager.GetString("TasksList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ticket List.
        /// </summary>
        internal static string TicketList {
            get {
                return ResourceManager.GetString("TicketList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Today Return Sales / Return Purchases.
        /// </summary>
        internal static string TodayReturnSalesReturnPurchases {
            get {
                return ResourceManager.GetString("TodayReturnSalesReturnPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Today Sales / Purchases.
        /// </summary>
        internal static string TodaySalesPurchases {
            get {
                return ResourceManager.GetString("TodaySalesPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total Expenses.
        /// </summary>
        internal static string TotalExpenses {
            get {
                return ResourceManager.GetString("TotalExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total / &lt;br/&gt; Payable.
        /// </summary>
        internal static string TotalPayable {
            get {
                return ResourceManager.GetString("TotalPayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total Purchases.
        /// </summary>
        internal static string TotalPurchases {
            get {
                return ResourceManager.GetString("TotalPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total Purchase&apos;s Per Day.
        /// </summary>
        internal static string TotalPurchasesPerDay {
            get {
                return ResourceManager.GetString("TotalPurchasesPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total Purchase&apos;s Per Month.
        /// </summary>
        internal static string TotalPurchasesPerMonth {
            get {
                return ResourceManager.GetString("TotalPurchasesPerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total / &lt;br/&gt; Receivable.
        /// </summary>
        internal static string TotalReceivable {
            get {
                return ResourceManager.GetString("TotalReceivable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total Return Purchases.
        /// </summary>
        internal static string TotalReturnPurchases {
            get {
                return ResourceManager.GetString("TotalReturnPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total Return Sales.
        /// </summary>
        internal static string TotalReturnSales {
            get {
                return ResourceManager.GetString("TotalReturnSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total Revenue.
        /// </summary>
        internal static string TotalRevenue {
            get {
                return ResourceManager.GetString("TotalRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total Sales.
        /// </summary>
        internal static string TotalSales {
            get {
                return ResourceManager.GetString("TotalSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total Sale&apos;s Per Day.
        /// </summary>
        internal static string TotalSalesPerDay {
            get {
                return ResourceManager.GetString("TotalSalesPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total Sale&apos;s Per Month.
        /// </summary>
        internal static string TotalSalesPerMonth {
            get {
                return ResourceManager.GetString("TotalSalesPerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Transactions.
        /// </summary>
        internal static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Treshold Quantity.
        /// </summary>
        internal static string TresholdQuantity {
            get {
                return ResourceManager.GetString("TresholdQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trial Balance.
        /// </summary>
        internal static string TrialBalance {
            get {
                return ResourceManager.GetString("TrialBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update Customer.
        /// </summary>
        internal static string UpdateCustomer {
            get {
                return ResourceManager.GetString("UpdateCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update Product.
        /// </summary>
        internal static string UpdateProduct {
            get {
                return ResourceManager.GetString("UpdateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User Setting.
        /// </summary>
        internal static string UserSetting {
            get {
                return ResourceManager.GetString("UserSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User Types.
        /// </summary>
        internal static string UserTypes {
            get {
                return ResourceManager.GetString("UserTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
