//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т. д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените RESX-файл и снова запустите ResGen
    // с параметром /str или перестройте проект Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Account", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Переопределяет свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account Control.
        /// </summary>
        internal static string AccountControlTitle {
            get {
                return ResourceManager.GetString("AccountControlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account Head.
        /// </summary>
        internal static string AccountHeadTitle {
            get {
                return ResourceManager.GetString("AccountHeadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account Sub Control Name.
        /// </summary>
        internal static string AccountSubControlName {
            get {
                return ResourceManager.GetString("AccountSubControlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Activity.
        /// </summary>
        internal static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Account Control.
        /// </summary>
        internal static string AddAccountControl {
            get {
                return ResourceManager.GetString("AddAccountControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Account Head.
        /// </summary>
        internal static string AddAccountHead {
            get {
                return ResourceManager.GetString("AddAccountHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Account Sub Control.
        /// </summary>
        internal static string AddAccountSubControl {
            get {
                return ResourceManager.GetString("AddAccountSubControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add New User Type.
        /// </summary>
        internal static string AddNewUserType {
            get {
                return ResourceManager.GetString("AddNewUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add User Type.
        /// </summary>
        internal static string AddUserType {
            get {
                return ResourceManager.GetString("AddUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All Account Controls.
        /// </summary>
        internal static string AllAccountControls {
            get {
                return ResourceManager.GetString("AllAccountControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All Account Heads.
        /// </summary>
        internal static string AllAccountHeads {
            get {
                return ResourceManager.GetString("AllAccountHeads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All Account Sub Controls.
        /// </summary>
        internal static string AllAccountSubControls {
            get {
                return ResourceManager.GetString("AllAccountSubControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All User Types.
        /// </summary>
        internal static string AllUserTypes {
            get {
                return ResourceManager.GetString("AllUserTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Code.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contact №.
        /// </summary>
        internal static string ContactNo {
            get {
                return ResourceManager.GetString("ContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Control Account.
        /// </summary>
        internal static string ControlAccount {
            get {
                return ResourceManager.GetString("ControlAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create User.
        /// </summary>
        internal static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete User Type.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to delete this User Type?.
        /// </summary>
        internal static string DeleteQuestion {
            get {
                return ResourceManager.GetString("DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit Account Control.
        /// </summary>
        internal static string EditAccountControl {
            get {
                return ResourceManager.GetString("EditAccountControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit Account Head.
        /// </summary>
        internal static string EditAccountHead {
            get {
                return ResourceManager.GetString("EditAccountHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit Sub Control.
        /// </summary>
        internal static string EditSubControl {
            get {
                return ResourceManager.GetString("EditSubControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit User Type.
        /// </summary>
        internal static string EditUserType {
            get {
                return ResourceManager.GetString("EditUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter Account Head ID.
        /// </summary>
        internal static string EnterAccountHeadID {
            get {
                return ResourceManager.GetString("EnterAccountHeadID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Full Name.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Head Account.
        /// </summary>
        internal static string HeadAccount {
            get {
                return ResourceManager.GetString("HeadAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Head Code.
        /// </summary>
        internal static string HeadCode {
            get {
                return ResourceManager.GetString("HeadCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manage Transactions.
        /// </summary>
        internal static string ManageTransactions {
            get {
                return ResourceManager.GetString("ManageTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Account Control.
        /// </summary>
        internal static string NewAccountControl {
            get {
                return ResourceManager.GetString("NewAccountControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Account Head.
        /// </summary>
        internal static string NewAccountHead {
            get {
                return ResourceManager.GetString("NewAccountHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Account Setting.
        /// </summary>
        internal static string NewAccountSetting {
            get {
                return ResourceManager.GetString("NewAccountSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Account Sub Control.
        /// </summary>
        internal static string NewAccountSubControl {
            get {
                return ResourceManager.GetString("NewAccountSubControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Account Sub Control Name.
        /// </summary>
        internal static string NewAccountSubControlName {
            get {
                return ResourceManager.GetString("NewAccountSubControlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter New Contact №.
        /// </summary>
        internal static string NewContactNo {
            get {
                return ResourceManager.GetString("NewContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter New Email.
        /// </summary>
        internal static string NewEmail {
            get {
                return ResourceManager.GetString("NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter New Full Name.
        /// </summary>
        internal static string NewFullName {
            get {
                return ResourceManager.GetString("NewFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter New Password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter New Status.
        /// </summary>
        internal static string NewStatus {
            get {
                return ResourceManager.GetString("NewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter New User Name.
        /// </summary>
        internal static string NewUserName {
            get {
                return ResourceManager.GetString("NewUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter New User Type.
        /// </summary>
        internal static string NewUserTypeID {
            get {
                return ResourceManager.GetString("NewUserTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Account Head.
        /// </summary>
        internal static string SelectAccountHead {
            get {
                return ResourceManager.GetString("SelectAccountHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Activity.
        /// </summary>
        internal static string SelectActivity {
            get {
                return ResourceManager.GetString("SelectActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Control Account.
        /// </summary>
        internal static string SelectControlAccount {
            get {
                return ResourceManager.GetString("SelectControlAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Head Account.
        /// </summary>
        internal static string SelectHeadAccount {
            get {
                return ResourceManager.GetString("SelectHeadAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Sub Account.
        /// </summary>
        internal static string SelectSubAccount {
            get {
                return ResourceManager.GetString("SelectSubAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Sub Control Account.
        /// </summary>
        internal static string SelectSubControlAccount {
            get {
                return ResourceManager.GetString("SelectSubControlAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set Accounting Flow.
        /// </summary>
        internal static string SetAccountingFlow {
            get {
                return ResourceManager.GetString("SetAccountingFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sub Account.
        /// </summary>
        internal static string SubAccount {
            get {
                return ResourceManager.GetString("SubAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sub Control Account.
        /// </summary>
        internal static string SubControlAccount {
            get {
                return ResourceManager.GetString("SubControlAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update User.
        /// </summary>
        internal static string UpdateUser {
            get {
                return ResourceManager.GetString("UpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User Name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User Type.
        /// </summary>
        internal static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User Type Details.
        /// </summary>
        internal static string UserTypeDetails {
            get {
                return ResourceManager.GetString("UserTypeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User Type.
        /// </summary>
        internal static string UserTypeID {
            get {
                return ResourceManager.GetString("UserTypeID", resourceCulture);
            }
        }
    }
}
