//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    public partial class tblSupplierReturnInvoiceDetail
    {
        public int SupplierReturnInvoiceDetailID { get; set; }
        public int SupplierInvoiceID { get; set; }
        public int SupplierInvoiceDetailID { get; set; }
        public int SupplierReturnInvoiceID { get; set; }
        public int ProductID { get; set; }
        public int PurchaseReturnQuantity { get; set; }
        public double PurchaseReturnUnitPrice { get; set; }

        public virtual tblStock tblStock { get; set; }
        public virtual tblSupplierInvoice tblSupplierInvoice { get; set; }
        public virtual tblSupplierInvoiceDetail tblSupplierInvoiceDetail { get; set; }
        public virtual tblSupplierReturnInvoice tblSupplierReturnInvoice { get; set; }
    }
}
