//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblSupplierPayment
    {
        [Key]
        public int SupplierPaymentID { get; set; }

        [Required(ErrorMessage = "Supplier ID is required.")]
        public int SupplierID { get; set; }

        [Required(ErrorMessage = "Supplier Invoice ID is required.")]
        public int SupplierInvoiceID { get; set; }

        [Required(ErrorMessage = "Company ID is required.")]
        public int CompanyID { get; set; }

        [Required(ErrorMessage = "Branch ID is required.")]
        public int BranchID { get; set; }

        [Required(ErrorMessage = "Invoice No is required.")]
        [StringLength(50, ErrorMessage = "Invoice No cannot be longer than 50 characters.")]
        public string InvoiceNo { get; set; }

        [Required(ErrorMessage = "Total Amount is required.")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Total Amount must be greater than 0.")]
        public double TotalAmount { get; set; }

        [Required(ErrorMessage = "Payment Amount is required.")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Payment Amount must be greater than 0.")]
        public double PaymentAmount { get; set; }

        [Required(ErrorMessage = "Remaining Balance is required.")]
        [Range(0.0, double.MaxValue, ErrorMessage = "Remaining Balance must be non-negative.")]
        public double RemainingBalance { get; set; }

        [Required(ErrorMessage = "User ID is required.")]
        public int UserID { get; set; }

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> InvoiceDate { get; set; }

        public virtual tblSupplier tblSupplier { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
