//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т. д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените RESX-файл и снова запустите ResGen
    // с параметром /str или перестройте проект Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Purchase {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Purchase() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Purchase", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Переопределяет свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Item.
        /// </summary>
        internal static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на After Return (Total Amount).
        /// </summary>
        internal static string AfterReturnTotalAmount {
            get {
                return ResourceManager.GetString("AfterReturnTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All Return Purchases (Pending Return Payment).
        /// </summary>
        internal static string AllReturnPurchasesPendingReturnPayment {
            get {
                return ResourceManager.GetString("AllReturnPurchasesPendingReturnPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Amount After Return.
        /// </summary>
        internal static string AmountAfterReturn {
            get {
                return ResourceManager.GetString("AmountAfterReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Conatct №.
        /// </summary>
        internal static string ConatctNo {
            get {
                return ResourceManager.GetString("ConatctNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contact №.
        /// </summary>
        internal static string ContactNo {
            get {
                return ResourceManager.GetString("ContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Created By.
        /// </summary>
        internal static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current Remaining Amount.
        /// </summary>
        internal static string CurrentRemainingAmount {
            get {
                return ResourceManager.GetString("CurrentRemainingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Custom Base Purchase`s History.
        /// </summary>
        internal static string CustomBasePurchasesHistory {
            get {
                return ResourceManager.GetString("CustomBasePurchasesHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Custom Base Sale`s History.
        /// </summary>
        internal static string CustomBaseSalesHistory {
            get {
                return ResourceManager.GetString("CustomBaseSalesHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter Payment`s Details.
        /// </summary>
        internal static string EnterPaymentsDetails {
            get {
                return ResourceManager.GetString("EnterPaymentsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter Purchase Invoice №.
        /// </summary>
        internal static string EnterPurchaseInvoiceNo {
            get {
                return ResourceManager.GetString("EnterPurchaseInvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter Return Payment`s Details.
        /// </summary>
        internal static string EnterReturnPaymentsDetails {
            get {
                return ResourceManager.GetString("EnterReturnPaymentsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finilize Purchase.
        /// </summary>
        internal static string FinilizePurchase {
            get {
                return ResourceManager.GetString("FinilizePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finilize Purchasing.
        /// </summary>
        internal static string FinilizePurchasing {
            get {
                return ResourceManager.GetString("FinilizePurchasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GRAND TOTAL.
        /// </summary>
        internal static string GRANDTOTAL {
            get {
                return ResourceManager.GetString("GRANDTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invoice.
        /// </summary>
        internal static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invoice Date.
        /// </summary>
        internal static string InvoiceDate {
            get {
                return ResourceManager.GetString("InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invoice №.
        /// </summary>
        internal static string InvoiceNo {
            get {
                return ResourceManager.GetString("InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is Purchase Payment Paid?.
        /// </summary>
        internal static string IsPurchasePaymentPaid {
            get {
                return ResourceManager.GetString("IsPurchasePaymentPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is Return Purchase Payment Paid?.
        /// </summary>
        internal static string IsReturnPurchasePaymentPaid {
            get {
                return ResourceManager.GetString("IsReturnPurchasePaymentPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Item Cost.
        /// </summary>
        internal static string ItemCost {
            get {
                return ResourceManager.GetString("ItemCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Item №.
        /// </summary>
        internal static string ItemNo {
            get {
                return ResourceManager.GetString("ItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Item`s.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Items List.
        /// </summary>
        internal static string ItemsList {
            get {
                return ResourceManager.GetString("ItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No History.
        /// </summary>
        internal static string NoHistory {
            get {
                return ResourceManager.GetString("NoHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No Payment Record.
        /// </summary>
        internal static string NoPaymentRecord {
            get {
                return ResourceManager.GetString("NoPaymentRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paid Amount.
        /// </summary>
        internal static string PaidAmount {
            get {
                return ResourceManager.GetString("PaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pay Amount.
        /// </summary>
        internal static string PayAmount {
            get {
                return ResourceManager.GetString("PayAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pay History.
        /// </summary>
        internal static string PayHistory {
            get {
                return ResourceManager.GetString("PayHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Payment Amount.
        /// </summary>
        internal static string PaymentAmount {
            get {
                return ResourceManager.GetString("PaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Payment Date.
        /// </summary>
        internal static string PaymentDate {
            get {
                return ResourceManager.GetString("PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Payroll.
        /// </summary>
        internal static string Payroll {
            get {
                return ResourceManager.GetString("Payroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Previous Remaining Amount.
        /// </summary>
        internal static string PreviousRemainingAmount {
            get {
                return ResourceManager.GetString("PreviousRemainingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Print Date.
        /// </summary>
        internal static string PrintDate {
            get {
                return ResourceManager.GetString("PrintDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Print Invoice.
        /// </summary>
        internal static string PrintInvoice {
            get {
                return ResourceManager.GetString("PrintInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Purchase Description.
        /// </summary>
        internal static string PurchaseDescription {
            get {
                return ResourceManager.GetString("PurchaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Purchase Details.
        /// </summary>
        internal static string PurchaseDetails {
            get {
                return ResourceManager.GetString("PurchaseDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Purchase Invoice.
        /// </summary>
        internal static string PurchaseInvoice {
            get {
                return ResourceManager.GetString("PurchaseInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Purchase Invoice Payment Detail.
        /// </summary>
        internal static string PurchaseInvoicePaymentDetail {
            get {
                return ResourceManager.GetString("PurchaseInvoicePaymentDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Purchase Paid Details.
        /// </summary>
        internal static string PurchasePaidDetails {
            get {
                return ResourceManager.GetString("PurchasePaidDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Purchase Payment.
        /// </summary>
        internal static string PurchasePayment {
            get {
                return ResourceManager.GetString("PurchasePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Purchase Products Detail.
        /// </summary>
        internal static string PurchaseProductsDetail {
            get {
                return ResourceManager.GetString("PurchaseProductsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Purchase Qty.
        /// </summary>
        internal static string PurchaseQty {
            get {
                return ResourceManager.GetString("PurchaseQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Purchase Return Details.
        /// </summary>
        internal static string PurchaseReturnDetails {
            get {
                return ResourceManager.GetString("PurchaseReturnDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Purchase`s Payment Pending.
        /// </summary>
        internal static string PurchasesPaymentPending {
            get {
                return ResourceManager.GetString("PurchasesPaymentPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Purchasing.
        /// </summary>
        internal static string Purchasing {
            get {
                return ResourceManager.GetString("Purchasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remaining Balance.
        /// </summary>
        internal static string RemainingBalance {
            get {
                return ResourceManager.GetString("RemainingBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remaining Return.
        /// </summary>
        internal static string RemainingReturn {
            get {
                return ResourceManager.GetString("RemainingReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remaining Total Balance.
        /// </summary>
        internal static string RemainingTotalBalance {
            get {
                return ResourceManager.GetString("RemainingTotalBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retrive Purchase`s Record.
        /// </summary>
        internal static string RetrivePurchasesRecord {
            get {
                return ResourceManager.GetString("RetrivePurchasesRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return Amount.
        /// </summary>
        internal static string ReturnAmount {
            get {
                return ResourceManager.GetString("ReturnAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return Payment.
        /// </summary>
        internal static string ReturnPayment {
            get {
                return ResourceManager.GetString("ReturnPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return (Payment Amount).
        /// </summary>
        internal static string ReturnPaymentAmount {
            get {
                return ResourceManager.GetString("ReturnPaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return Products Detail.
        /// </summary>
        internal static string ReturnProductsDetail {
            get {
                return ResourceManager.GetString("ReturnProductsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return Products (Total Amount).
        /// </summary>
        internal static string ReturnProductsTotalAmount {
            get {
                return ResourceManager.GetString("ReturnProductsTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return Purchase`s Payment Pending.
        /// </summary>
        internal static string ReturnPurchasesPaymentPending {
            get {
                return ResourceManager.GetString("ReturnPurchasesPaymentPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return (Purchase Total Amount).
        /// </summary>
        internal static string ReturnPurchaseTotalAmount {
            get {
                return ResourceManager.GetString("ReturnPurchaseTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return Qty.
        /// </summary>
        internal static string ReturnQty {
            get {
                return ResourceManager.GetString("ReturnQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return Remaining Amount.
        /// </summary>
        internal static string ReturnRemainingAmount {
            get {
                return ResourceManager.GetString("ReturnRemainingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return (Remaining Balance).
        /// </summary>
        internal static string ReturnRemainingBalance {
            get {
                return ResourceManager.GetString("ReturnRemainingBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return Total.
        /// </summary>
        internal static string ReturnTotal {
            get {
                return ResourceManager.GetString("ReturnTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return (Total Amount).
        /// </summary>
        internal static string ReturnTotalAmount {
            get {
                return ResourceManager.GetString("ReturnTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search Purchase By Invoice №.
        /// </summary>
        internal static string SearchPurchaseByInvoiceNo {
            get {
                return ResourceManager.GetString("SearchPurchaseByInvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select From Date.
        /// </summary>
        internal static string SelectFromDate {
            get {
                return ResourceManager.GetString("SelectFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Product.
        /// </summary>
        internal static string SelectProduct {
            get {
                return ResourceManager.GetString("SelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Range (From Date and To Date).
        /// </summary>
        internal static string SelectRangeFromDateAndToDate {
            get {
                return ResourceManager.GetString("SelectRangeFromDateAndToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select To Date.
        /// </summary>
        internal static string SelectToDate {
            get {
                return ResourceManager.GetString("SelectToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set Payment.
        /// </summary>
        internal static string SetPayment {
            get {
                return ResourceManager.GetString("SetPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Submit Payment.
        /// </summary>
        internal static string SubmitPayment {
            get {
                return ResourceManager.GetString("SubmitPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Submit Return.
        /// </summary>
        internal static string SubmitReturn {
            get {
                return ResourceManager.GetString("SubmitReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Supplier.
        /// </summary>
        internal static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total Amount.
        /// </summary>
        internal static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total Purchase Amount.
        /// </summary>
        internal static string TotalPurchaseAmount {
            get {
                return ResourceManager.GetString("TotalPurchaseAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unit Price.
        /// </summary>
        internal static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View Details.
        /// </summary>
        internal static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
    }
}
